/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ta_pdkp_enrico;

import javax.swing.JOptionPane;

/**
 *
 * @author icoto
 */
public class Simulasi_Rapor extends javax.swing.JFrame {

    String gender ;
    String major ;
    public Simulasi_Rapor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nimTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        majorCbx = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        costTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        kelasTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        absenTxt = new javax.swing.JTextField();
        TaskTxt = new javax.swing.JTextField();
        UTStxt = new javax.swing.JTextField();
        UAStxt = new javax.swing.JTextField();
        akhirTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gradeTxt = new javax.swing.JTextField();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        totalAbsenTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        persentaskTxt = new javax.swing.JTextField();
        persenuasTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        persenutsTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        persenAbsenTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        countButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        tableButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTxt = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        regTxt = new javax.swing.JTextField();
        UASCbTxt = new javax.swing.JTextField();
        UTSCbTxt = new javax.swing.JTextField();
        regCb = new javax.swing.JCheckBox();
        utsCb = new javax.swing.JCheckBox();
        uasCb = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulasi Nilai Rapor");

        jPanel2.setBackground(new java.awt.Color(52, 152, 219));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nama");

        namaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTxtActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NIS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Jenis Kelamin");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kelas");

        majorCbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        majorCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih--", "MIPA", "IPS", "Bahasa" }));
        majorCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majorCbxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Biaya / Bulan");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jurusan ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nilai Kehadiran ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nilai Tugas ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nilai UTS");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nilai UAS");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Nilai Akhir");

        absenTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absenTxtActionPerformed(evt);
            }
        });

        TaskTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskTxtActionPerformed(evt);
            }
        });

        UTStxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UTStxtActionPerformed(evt);
            }
        });

        UAStxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UAStxtActionPerformed(evt);
            }
        });

        akhirTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akhirTxtActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Grade");

        gradeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeTxtActionPerformed(evt);
            }
        });

        buttonGroup1.add(maleBtn);
        maleBtn.setText("Laki - Laki");

        buttonGroup1.add(femaleBtn);
        femaleBtn.setText("Perempuan");

        jLabel14.setText("% dari ");

        persentaskTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persentaskTxtActionPerformed(evt);
            }
        });

        persenuasTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenuasTxtActionPerformed(evt);
            }
        });

        jLabel15.setText("% dari ");

        jLabel16.setText("% dari ");

        persenutsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persenutsTxtActionPerformed(evt);
            }
        });

        jLabel17.setText("% dari ");

        jLabel18.setText("% dari ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("/");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nimTxt)
                            .addComponent(namaTxt)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(femaleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(maleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kelasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(majorCbx, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(costTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(persenAbsenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(persentaskTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TaskTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(totalAbsenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(absenTxt))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(persenutsTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(persenuasTxt))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UTStxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(UAStxt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(gradeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(akhirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(absenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAbsenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(persenAbsenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel8)
                        .addComponent(TaskTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(persentaskTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(maleBtn)
                        .addComponent(UTStxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(persenutsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(femaleBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UAStxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(persenuasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(majorCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(costTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(akhirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(kelasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gradeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(46, 204, 113));

        countButton.setText("Hitung");
        countButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Hapus");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        tableButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tableButton.setText("Ke Tabel");
        tableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableButtonActionPerformed(evt);
            }
        });

        outputTxt.setColumns(20);
        outputTxt.setRows(5);
        jScrollPane1.setViewportView(outputTxt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tableButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(clearButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(countButton)
                        .addGap(31, 31, 31)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tableButton)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(155, 89, 182));

        regTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        regTxt.setText("0");
        regTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regTxtActionPerformed(evt);
            }
        });

        UASCbTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UASCbTxt.setText("0");

        UTSCbTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        UTSCbTxt.setText("0");

        regCb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        regCb.setText("Reg.");
        regCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCbActionPerformed(evt);
            }
        });

        utsCb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        utsCb.setText("UTS");
        utsCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utsCbActionPerformed(evt);
            }
        });

        uasCb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        uasCb.setText("UAS");
        uasCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uasCbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(regCb, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utsCb, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uasCb, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UASCbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UTSCbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regTxt)
                    .addComponent(regCb, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(utsCb, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(UTSCbTxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uasCb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UASCbTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setForeground(new java.awt.Color(51, 255, 204));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel10.setText("Simulasi Nilai Rapor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akhirTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akhirTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akhirTxtActionPerformed

    private void UAStxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UAStxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UAStxtActionPerformed

    private void UTStxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UTStxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UTStxtActionPerformed

    private void TaskTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaskTxtActionPerformed

    private void absenTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absenTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_absenTxtActionPerformed

    private void namaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTxtActionPerformed

    private void regTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regTxtActionPerformed
        
    }//GEN-LAST:event_regTxtActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
       namaTxt.setText("");
       nimTxt.setText("");
       costTxt.setText("");
       kelasTxt.setText("");
       persenAbsenTxt.setText("");
       absenTxt.setText("");
       totalAbsenTxt.setText("");
       TaskTxt.setText("");
       persentaskTxt.setText("");
       UTStxt.setText("");
       persenutsTxt.setText("");
       UAStxt.setText("");
       persenuasTxt.setText("");
       akhirTxt.setText("");
       gradeTxt.setText("");
       regTxt.setText("0");
       maleBtn.setSelected(false);
       femaleBtn.setSelected(false);
       UTSCbTxt.setText("0");
       UASCbTxt.setText("0");
       outputTxt.setText("");
       majorCbx.setSelectedIndex(0);
       regCb.setSelected(false);
       utsCb.setSelected(false);
       uasCb.setSelected(false);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void majorCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majorCbxActionPerformed
        switch (majorCbx.getSelectedIndex()) {
            case 0 -> costTxt.setText("");
            case 1 -> costTxt.setText("300000");
            case 2 -> costTxt.setText("250000");
            default -> costTxt.setText("200000");
        }
    }//GEN-LAST:event_majorCbxActionPerformed

    private void countButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countButtonActionPerformed
        if (namaTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama belum diisi");
        }if (nimTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"NIS belum diisi");
        }if ((femaleBtn.isSelected() == false) && maleBtn.isSelected() == false){
            JOptionPane.showMessageDialog(null,"Jenis Kelamin belum terpilih");
        }if (majorCbx.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Jurusan belum terpilih");
        }if (kelasTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Kelas belum diisi");
        }if (absenTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Jumlah kehadiran belum diisi");
        }if (TaskTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nilai tugas belum diisi");
        }if (UTStxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nilai UTS belum diisi");
        }if (UAStxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nilai UAS  belum diisi");
        }if (persenAbsenTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Persentase nilai absen belum diisi");  
        }if (totalAbsenTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Total jumlah absen belum diisi");  
        }if (persentaskTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Persentase nilai tugas belum diisi");  
        }if (persenutsTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Persentase nilai UTS belum diisi");  
        }if (persenuasTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Persentase nilai UAS belum diisi");  
        }if (Float.valueOf(persenAbsenTxt.getText()) + Float.valueOf(persentaskTxt.getText()) + Float.valueOf(persenuasTxt.getText()) 
                + Float.valueOf(persenutsTxt.getText()) != 100){
            JOptionPane.showMessageDialog(null,"Total Persentase tidak berjumlah 100 Persen");
        }
        double absenValue = Double.parseDouble(absenTxt.getText()),
               totalAbsen = Double.parseDouble(totalAbsenTxt.getText()),
               taskValue = Double.parseDouble(TaskTxt.getText()),
               utsValue = Double.parseDouble(UTStxt.getText()),
               uasValue = Double.parseDouble(UAStxt.getText()),
               regValue = Double.parseDouble(regTxt.getText()),
               uasCbValue = Double.parseDouble(UTSCbTxt.getText()),
               utsCbValue = Double.parseDouble(UASCbTxt.getText()),
               costValue = Double.parseDouble(costTxt.getText()),
               persenTask = Double.parseDouble(persentaskTxt.getText()),
               persenAbsen = Double.parseDouble(persenAbsenTxt.getText()),
               persenUAS = Double.parseDouble(persenuasTxt.getText()),
               persenUTS = Double.parseDouble(persenutsTxt.getText()),
               akhirValue, total ;
        akhirValue = (((absenValue + (100-totalAbsen))* persenAbsen/100) + (taskValue * persenTask/100)
                        + (utsValue * persenUTS/100) + (uasValue * persenUAS/100));
        akhirTxt.setText("" + akhirValue);
        
        if (akhirValue < 50){
            gradeTxt.setText("E");
        }else if (akhirValue < 60){
            gradeTxt.setText("D");
        }else if (akhirValue < 70){
            gradeTxt.setText("C");
        }else if (akhirValue < 80){
            gradeTxt.setText("B");
        }else {
            gradeTxt.setText("A");
        }
        
        if (maleBtn.isSelected()){
            femaleBtn.setSelected(false);
             gender = "Laki - Laki";
        }else {
            femaleBtn.setSelected(true);
            maleBtn.setSelected(false);
            gender = "Perempuan";
        }
        
        major = switch (majorCbx.getSelectedIndex()) {
            case 0 -> "-";
            case 1 -> "MIPA";
            case 2 -> "IPS";
            default -> "Bahasa";
        };
        
        total = regValue + utsCbValue + uasCbValue + costValue;
            
         outputTxt.setText("Nama \t: "+namaTxt.getText() + "\nNIM \t: "
                            + nimTxt.getText() + "\nJenis Kelamin \t: "
                            + gender.toString() + "\nJurusan \t: "+ major
                            + "\nKelas \t:" +kelasTxt.getText()+ "\nNilai Rapor \t: "
                            + akhirTxt.getText() + "\nGrade \t: " +
                              gradeTxt.getText() + "\nTotal Biaya \t:" + total); 
                         
    }//GEN-LAST:event_countButtonActionPerformed
    
    private void gradeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeTxtActionPerformed
        
    }//GEN-LAST:event_gradeTxtActionPerformed

    private void regCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCbActionPerformed
        if (regCb.isSelected()){
            regTxt.setText("150000");
        }else {
            regTxt.setText("0");
        }
    }//GEN-LAST:event_regCbActionPerformed

    private void utsCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utsCbActionPerformed
        if (utsCb.isSelected()){
            UTSCbTxt.setText("200000");
        }else {
            UTSCbTxt.setText("0");
        }
    }//GEN-LAST:event_utsCbActionPerformed

    private void uasCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uasCbActionPerformed
        if (uasCb.isSelected()){
            UASCbTxt.setText("250000");
        }else {
            UASCbTxt.setText("0");
        }
    }//GEN-LAST:event_uasCbActionPerformed

    private void tableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableButtonActionPerformed
          
        if (namaTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nama belum diisi");
        }if (nimTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"NIS belum diisi");
        }if ((femaleBtn.isSelected() == false) && maleBtn.isSelected() == false){
            JOptionPane.showMessageDialog(null,"Jenis Kelamin belum terpilih");
        }if (majorCbx.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null,"Jurusan belum terpilih");
        }if (kelasTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Kelas belum diisi");
        }if (absenTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Jumlah kehadiran belum diisi");
        }if (TaskTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nilai tugas belum diisi");
        }if (UTStxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nilai UTS belum diisi");
        }if (UAStxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Nilai UAS  belum diisi");
        }if (persenAbsenTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Persentase nilai absen belum diisi");  
        }if (totalAbsenTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Total jumlah absen belum diisi");  
        }if (persentaskTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Persentase nilai tugas belum diisi");  
        }if (persenutsTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Persentase nilai UTS belum diisi");  
        }if (persenuasTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Persentase nilai UAS belum diisi");  
        }if (Float.valueOf(persenAbsenTxt.getText()) + Float.valueOf(persentaskTxt.getText()) + Float.valueOf(persenuasTxt.getText()) 
                + Float.valueOf(persenutsTxt.getText()) != 100){
            JOptionPane.showMessageDialog(null,"Total Persentase tidak berjumlah 100 Persen");
        }if (akhirTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Tekan tombol HITUNG terlebih dahulu !");
        }else {
            if (maleBtn.isSelected()){
            femaleBtn.setSelected(false);
             gender = "Laki - Laki";
            }else {
            femaleBtn.setSelected(true);
            maleBtn.setSelected(false);
            gender = "Perempuan";
            }      
        
            major = switch (majorCbx.getSelectedIndex()) {
            case 0 -> "-";
            case 1 -> "MIPA";
            case 2 -> "IPS";
            default -> "Bahasa";
            };
            double regValue = Double.parseDouble(regTxt.getText()),
               uasCbValue = Double.parseDouble(UTSCbTxt.getText()),
               utsCbValue = Double.parseDouble(UASCbTxt.getText()),
               costValue = Double.parseDouble(costTxt.getText()),
                    
               total ;
            total = (regValue + utsCbValue + uasCbValue + costValue);
            DataTable dataTabel = new DataTable(namaTxt.getText(), nimTxt.getText(),
                                   gender , major, kelasTxt.getText(), akhirTxt.getText(), gradeTxt.getText(), total);
            dataTabel.setVisible(true);
      
        }
    }//GEN-LAST:event_tableButtonActionPerformed

    private void persentaskTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persentaskTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persentaskTxtActionPerformed

    private void persenuasTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenuasTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persenuasTxtActionPerformed

    private void persenutsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persenutsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_persenutsTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulasi_Rapor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulasi_Rapor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulasi_Rapor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulasi_Rapor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulasi_Rapor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TaskTxt;
    private javax.swing.JTextField UASCbTxt;
    private javax.swing.JTextField UAStxt;
    private javax.swing.JTextField UTSCbTxt;
    private javax.swing.JTextField UTStxt;
    private javax.swing.JTextField absenTxt;
    private javax.swing.JTextField akhirTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField costTxt;
    private javax.swing.JButton countButton;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JTextField gradeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kelasTxt;
    private javax.swing.JComboBox<String> majorCbx;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField nimTxt;
    private javax.swing.JTextArea outputTxt;
    private javax.swing.JTextField persenAbsenTxt;
    private javax.swing.JTextField persentaskTxt;
    private javax.swing.JTextField persenuasTxt;
    private javax.swing.JTextField persenutsTxt;
    private javax.swing.JCheckBox regCb;
    private javax.swing.JTextField regTxt;
    private javax.swing.JButton tableButton;
    private javax.swing.JTextField totalAbsenTxt;
    private javax.swing.JCheckBox uasCb;
    private javax.swing.JCheckBox utsCb;
    // End of variables declaration//GEN-END:variables
}
